@startuml
node "Budget Buddy" {
    [Ui (command line interface)]
    [Logic]
    [Data]
    [Storage]

}

[User] -> [Ui (command line interface)]
[Logic] <--> [Ui (command line interface)]
[Logic] <--> [Data]
[Data] <--> [Storage] : Json format
[Logic] <--> [Storage]
@enduml
