@startuml
hide footbox
hide circle
skinparam groupInheritance 2
skinparam classAttributeIconSize 0

class "{abstract} \n Item" {
    +name: String
    +amount: Double
}

class Budget {
}

class Deposit {
    +id: Integer
    +date: LocalDate
}

class Expense {
    +id: Integer
    +category: String
    +date: LocalDate
}

"{abstract} \n Item" <|-down- Budget
"{abstract} \n Item" <|-down- Deposit
"{abstract} \n Item" <|-down- Expense
@enduml