@startuml

hide footbox

 -> ":StatsCommand":

activate ":StatsCommand"
":StatsCommand" -> ":StatsCommand": execute(data, ui)
activate  ":StatsCommand"
":StatsCommand" -> ":StatsAction" :statsAction
activate ":StatsAction"

":StatsAction" -> ":data" :getBudgets()
activate ":data"
return budgets: ArrayList<Budget>
deactivate ":data"
":StatsAction" -> ":data" :getDeposits()
activate ":data"
return deposits: ArrayList<Deposit>
deactivate ":data"
":StatsAction" -> ":data" :getExpenses()
activate ":data"
return expenses: ArrayList<Expense>
deactivate ":data"


deactivate ":StatsAction"



alt action is show
":StatsCommand" -> ":StatsCommand" :executeShowStats(statsAction, optionalParams)
activate ":StatsCommand"


":StatsCommand" -> ":LocalDate":
activate ":LocalDate"
":LocalDate" -> ":LocalDate": getMonthValue()
activate ":LocalDate"
return month: Integer
return month


":StatsCommand" -> ":LocalDate":
activate ":LocalDate"
":LocalDate" -> ":LocalDate": getYear()
activate ":LocalDate"
return year: Integer
return year

":StatsCommand" -> ":StatsAction" :month, year, showDeposit, showExpense
activate ":StatsAction"
":StatsAction" -> ":StatsAction" :showStats(month, year, showDeposit, showExpense)
activate ":StatsAction"
return
return

deactivate ":StatsCommand"

else action is help
":StatsCommand" -> ":StatsAction"
activate ":StatsCommand"
activate ":StatsAction"
":StatsAction" -> ":StatsAction" : statsHelp()
activate ":StatsAction"
return
return
deactivate ":StatsCommand"

end



deactivate ":StatsCommand"




@enduml