@startuml




class "{abstract} \n Command"  {
         +actions: String[]
         +requiredParamsList: Pair[][]
         +optionalParamsList: Pair[][]
         +name: CommandEnum
         +action: String
         +requiredParams: String[]
         +optionalParams: String[]

         +Command(CommandEnum name, String[] actions, Pair[][] requiredParamsList, Pair[][] optionalParamsList)
         +FindCommand(reviews: ReviewList, searchTerm: String)
         +void execute(Data data, Ui ui)
         +boolean isExit()
         +CommandEnum getCommandName()
            +String[] getActions()
            +String getAction()
            +int getActionNo(String action)
            +void setAction(String action)
            +void setParams(String[] requiredParams, String[] optionalParams)

}


class BudgetCommand {
    +ACTIONS: String[]
    +ACTIONS_REQUIRED_PARAMS: Pair[][]
    +ACTIONS_OPTIONAL_PARAMS: Pair[][]
     +void execute(Data data, Ui ui)
     +void executeBudgetDetail(BudgetAction budgetAction, String[] requiredParams, ArrayList<Expense> expenses)


     +void executeFindBudget(BudgetAction budgetAction, String[] requiredParams)

     +boolean isExit()
}

note right
 void executeBudgetHelp(), void executeAddBudget(),
 void executeSetBudget(), void executeDelBudget(),
 void executeListBudget() are the other methods under BudgetCommand

end note

class Data {
+ budgets: ArrayList<Budget>
+ deposits: ArrayList<Deposit>
+ expenses: ArrayList<Expense>
+ Data importData()
+ void exportData()

}

class Ui {
+ String readInput()
+ void printMessage(String... messages)
+ void printErrorMessage(String message)
+ void greetUser()
+ void byeUser()
}

class Budget {
    +Budget(String name, double amount)
}

class Expense {
    +date: LocalDate
    +category: String
    +Expense(String category, String name, double amount, LocalDate date)
    +String getCategory()
    +LocalDate getDate()
}

class Deposit {
    +date: LocalDate
    +Deposit(String name, double amount, LocalDate date)
    +LocalDate getDate()
}






"{abstract} \n Command" <-down- BudgetCommand
"{abstract} \n Command" <-right- Ui
"{abstract} \n Command" <-left- Data


"Budget" <-down-"\n0..  " Data
"Expense" <-right "0.. "Data
"Deposit" <-up-"0..  " Data



@enduml